# This contains the anti-cheat related configurations.

# How many ticks of history are contained in the client's rolling window for use when receiving corrections.
# At 20 ticks per second a history size of 40 means that a correction could still be processed with rewind with
# two seconds of two-way latency
# NOTE: This is not "that" important on Boar.
player-rewind-history-size-ticks: 20
  
# This is the tolerance of discrepancies between the Client and Server Player position. This helps prevent sending corrections too frequently
# NOTE: Again, Boar can handle small offset just fine and does account for lag, however keep in mind that Boar can't handle (that well)
# any offset smaller than 5.0E-5
player-position-acceptance-threshold: 1.0E-4

# Checks that you want Boar to disable.
# Check name should be in format "Name-Type" and if there is no type then "Name", ex: Reach-A (don't actually disable reach check lol).
disabled-checks: []

# Normally Boar will account for lag, that also including placing, if on the server side the block player place on is Air
# but on the client side the block player place on is a valid block, Boar going to allow the placement.
# However, if this config is true, Boar is going to forcefully rewind player and cancel the place if on the server side
# player block is Air.
# NOTE: THIS ONLY APPLIED FOR BLOCK PLACING.
ignore-ghost-block-place: false